services:
  web:
    build: .
    container_name: flask_app
    restart: always
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: flask_db
    restart: always
    environment:
      POSTGRES_DB: alestur_db
      POSTGRES_USER: alestur_user
      POSTGRES_PASSWORD: superpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: flask_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
volumes:
  postgres_data: