FROM python:3.11-slim

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn psycopg2-binary

CMD ["gunicorn", "--chdir", "/app", "--bind", "0.0.0.0:8000", "app:app"]