server {
    listen 80;
    server_name alesturslimitadaapi.top www.alesturslimitadaapi.top;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name alesturslimitadaapi.top www.alesturslimitadaapi.top;

    ssl_certificate /etc/letsencrypt/live/alesturslimitadaapi.top/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/alesturslimitadaapi.top/privkey.pem;

    location /archivos/ {
        alias /var/www/APIWPALESTUR/archivos/;
        autoindex off;
        add_header Content-Disposition "inline";
    }

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}